### ISSUE TITLE
Fix h1 heading padding

### ISSUE THREAD

**Issue by wilsonj806** [wilsonj806/maze-robot-documentation#1]
This is for tablet and mobile breakpoints (the big Maze Solving Robot Documentation heading)

Also, add the following in, since you have a `h1` header element already (syntax not exact)
```css
@media screen and (max width: 768px){
.nav-hdr{
    display:none;
}}
```
